<?php

/* Auto-generated by the web installer. */

define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'kusagba_hms');
define('DB_USER', 'root');
define('DB_PASS', '');
define('BASE_URL', '/kusagba');
define('APP_NAME', 'Kusagba General Hospital');
define('APP_CURRENCY', 'NGN');
define('TIMEZONE', 'Africa/Lagos');
define('APP_DEBUG', false);
define('INSTALLED', true);
